title: Ezlan
logo: /assets/img/haha.jpg
description: Hi! I'm Eizlan, a web develpor and linux lover from Malaysia. Please take a look around. .
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
