# Site settings
title: Ezlan | Dev
description: A blog my passion
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ezlan
user_description: New kid on the block. Eizlan is a Computer Science student with interest in computers, Web Development and passionate towards FOSS. He loves Linux and likes to promote it. Working as a freelancer, currently specialized in Laravel, GitHub, GitLab, Mysql, Heroku and Bootstrap.
user_title: Web Developer
email: eizs798@gmail.com
github_username:  Ezlan97

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
